
--------------------------------------------------------------------------------
-- TEST_OWNER.DIM_TEST

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TEST_OWNER.DIM_TEST CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;
/



CREATE TABLE TEST_OWNER.DIM_TEST
( TEST_COLUMN_1                       INTEGER              NULL
, TEST_COLUMN_2                       VARCHAR2(20)         NULL
)
COMPRESS FOR OLTP
TABLESPACE TEST_DATA
;


GRANT DELETE, INSERT, SELECT, UPDATE ON TEST_OWNER.DIM_TEST TO TEST_JOBS;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEST_OWNER.DIM_TEST TO TEST_OWNER_RW;
GRANT DELETE, INSERT, SELECT, UPDATE ON TEST_OWNER.DIM_TEST TO ETL_ADMIN;
GRANT SELECT ON TEST_OWNER.DIM_TEST TO TEST_OWNER_READ;
GRANT SELECT ON MTEST_OWNER.DIM_TEST TO MSTR_ADMIN;
GRANT SELECT, INSERT, UPDATE, ALTER, DELETE ON TEST_OWNER.DIM_TEST TO DEVELOPER_RW;

CREATE UNIQUE INDEX TEST_OWNER.IX_DIM_TEST_PK ON TEST_OWNER.DIM_TEST (TEST_COLUMN_1 ASC)
NOLOGGING
NOCOMPRESS
TABLESPACE TEST_DATA
;


ALTER TABLE TEST_OWNER.DIM_TEST ADD CONSTRAINT PK_DIM_TEST PRIMARY KEY (TEST_COLUMN_1) USING INDEX TEST_OWNER.IX_DIM_TEST_PK;


COMMENT ON TABLE  TEST_OWNER.DIM_TEST                                         IS 'Test Dimensional Table';
COMMENT ON COLUMN TEST_OWNER.DIM_TEST.TEST_COLUMN_1                           IS 'TEST COLUMN: COMMENT ONE';
COMMENT ON COLUMN TEST_OWNER.DIM_TEST.TEST_COLUMN_2                           IS 'TEST COLUMN: COMMENT TWO';

